--ALTER TABLE PCM_USERS ADD CONSTRAINT SQL120217135903349 UNIQUE (USERNAME);
ALTER TABLE PCM_AUTHORITIES ADD CONSTRAINT FK_4DUYQ3MMTRLDR30ORQ5HFCBXL FOREIGN KEY (USERNAME)
	REFERENCES PCM_USERS (USERNAME)